### ISSUE TITLE
fixed-effect estimate p-values in testEstimates() are from one-sided tests

### ISSUE THREAD

**Issue by wjchulme** [simongrund1/mitml#2]
For example, if `model_list` is a `list` of `merMod` objects from multiply imputed datasets, then extracting pooled p-values of fixed-effect estimates using `mice` and `mitml` gives different results:

    require(mice)
    require(mitml)
    mice_pval <- summary(mice::pool(mice::as.mira(model_list), method='other'))[ , 'Pr(>|t|)']
    mitml_pval <- mitml::testEstimates(model_list)$estimates[ , 'p.value']

    cbind(mice_pval, mitml_pval, mitml_pval*2)

Looking through the `testEstimates()` function, it's clear that `p` has not been multiplied by two:

    p <- 1 - pt(abs(t), df = v)

thus giving an (undirected) one-sided test. Shouldn't this be

    p <- 2*(1 - pt(abs(t), df = v))

instead?

**Comment by simongrund1** [comment]
Thanks for bringing this up. `testEstimates()` currently gives the p-value of the one-tailed test. As far as I am aware, there isn't a clear standard in statistical software, which is why I chose the one-tailed value intitially.

However, I agree that the two-tailed value is more common and what most users expect. I uploaded a patch that changes the default p-value in `testEstimates()` to the two-tailed value and renames it to `P(>|t|)` in order to align it with other software and to avoid confusion with earlier versions. Similarly, the p-values for multiparameter tests have been renamed to `P(>F)`.

**Comment by wjchulme** [comment]
No problem, just wanted to draw your attention to it, as it caught me out. The patch is a simple and effective solution. Thanks

I'd be surprised if there was any major statistical software reporting one-sided values for regression coefficients, but I'll admit I haven't bothered to check.
